/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubernetes-grafana-controller/pkg/apis/grafana/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeNotificationChannels implements NotificationChannelInterface
type FakeNotificationChannels struct {
	Fake *FakeGrafanaV1alpha1
	ns   string
}

var notificationchannelsResource = schema.GroupVersionResource{Group: "grafana.com", Version: "v1alpha1", Resource: "notificationchannels"}

var notificationchannelsKind = schema.GroupVersionKind{Group: "grafana.com", Version: "v1alpha1", Kind: "NotificationChannel"}

// Get takes name of the notificationChannel, and returns the corresponding notificationChannel object, and an error if there is any.
func (c *FakeNotificationChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.NotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(notificationchannelsResource, c.ns, name), &v1alpha1.NotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NotificationChannel), err
}

// List takes label and field selectors, and returns the list of NotificationChannels that match those selectors.
func (c *FakeNotificationChannels) List(opts v1.ListOptions) (result *v1alpha1.NotificationChannelList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(notificationchannelsResource, notificationchannelsKind, c.ns, opts), &v1alpha1.NotificationChannelList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.NotificationChannelList{ListMeta: obj.(*v1alpha1.NotificationChannelList).ListMeta}
	for _, item := range obj.(*v1alpha1.NotificationChannelList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested notificationChannels.
func (c *FakeNotificationChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(notificationchannelsResource, c.ns, opts))

}

// Create takes the representation of a notificationChannel and creates it.  Returns the server's representation of the notificationChannel, and an error, if there is any.
func (c *FakeNotificationChannels) Create(notificationChannel *v1alpha1.NotificationChannel) (result *v1alpha1.NotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(notificationchannelsResource, c.ns, notificationChannel), &v1alpha1.NotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NotificationChannel), err
}

// Update takes the representation of a notificationChannel and updates it. Returns the server's representation of the notificationChannel, and an error, if there is any.
func (c *FakeNotificationChannels) Update(notificationChannel *v1alpha1.NotificationChannel) (result *v1alpha1.NotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(notificationchannelsResource, c.ns, notificationChannel), &v1alpha1.NotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NotificationChannel), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeNotificationChannels) UpdateStatus(notificationChannel *v1alpha1.NotificationChannel) (*v1alpha1.NotificationChannel, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(notificationchannelsResource, "status", c.ns, notificationChannel), &v1alpha1.NotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NotificationChannel), err
}

// Delete takes name of the notificationChannel and deletes it. Returns an error if one occurs.
func (c *FakeNotificationChannels) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(notificationchannelsResource, c.ns, name), &v1alpha1.NotificationChannel{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeNotificationChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(notificationchannelsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.NotificationChannelList{})
	return err
}

// Patch applies the patch and returns the patched notificationChannel.
func (c *FakeNotificationChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.NotificationChannel, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(notificationchannelsResource, c.ns, name, pt, data, subresources...), &v1alpha1.NotificationChannel{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.NotificationChannel), err
}
