/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "kubernetes-grafana-controller/pkg/apis/grafana/v1alpha1"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeAlertNotifications implements AlertNotificationInterface
type FakeAlertNotifications struct {
	Fake *FakeGrafanaV1alpha1
	ns   string
}

var alertnotificationsResource = schema.GroupVersionResource{Group: "grafana.com", Version: "v1alpha1", Resource: "alertnotifications"}

var alertnotificationsKind = schema.GroupVersionKind{Group: "grafana.com", Version: "v1alpha1", Kind: "AlertNotification"}

// Get takes name of the alertNotification, and returns the corresponding alertNotification object, and an error if there is any.
func (c *FakeAlertNotifications) Get(name string, options v1.GetOptions) (result *v1alpha1.AlertNotification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(alertnotificationsResource, c.ns, name), &v1alpha1.AlertNotification{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertNotification), err
}

// List takes label and field selectors, and returns the list of AlertNotifications that match those selectors.
func (c *FakeAlertNotifications) List(opts v1.ListOptions) (result *v1alpha1.AlertNotificationList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(alertnotificationsResource, alertnotificationsKind, c.ns, opts), &v1alpha1.AlertNotificationList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.AlertNotificationList{ListMeta: obj.(*v1alpha1.AlertNotificationList).ListMeta}
	for _, item := range obj.(*v1alpha1.AlertNotificationList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested alertNotifications.
func (c *FakeAlertNotifications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(alertnotificationsResource, c.ns, opts))

}

// Create takes the representation of a alertNotification and creates it.  Returns the server's representation of the alertNotification, and an error, if there is any.
func (c *FakeAlertNotifications) Create(alertNotification *v1alpha1.AlertNotification) (result *v1alpha1.AlertNotification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(alertnotificationsResource, c.ns, alertNotification), &v1alpha1.AlertNotification{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertNotification), err
}

// Update takes the representation of a alertNotification and updates it. Returns the server's representation of the alertNotification, and an error, if there is any.
func (c *FakeAlertNotifications) Update(alertNotification *v1alpha1.AlertNotification) (result *v1alpha1.AlertNotification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(alertnotificationsResource, c.ns, alertNotification), &v1alpha1.AlertNotification{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertNotification), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeAlertNotifications) UpdateStatus(alertNotification *v1alpha1.AlertNotification) (*v1alpha1.AlertNotification, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(alertnotificationsResource, "status", c.ns, alertNotification), &v1alpha1.AlertNotification{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertNotification), err
}

// Delete takes name of the alertNotification and deletes it. Returns an error if one occurs.
func (c *FakeAlertNotifications) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(alertnotificationsResource, c.ns, name), &v1alpha1.AlertNotification{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeAlertNotifications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(alertnotificationsResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.AlertNotificationList{})
	return err
}

// Patch applies the patch and returns the patched alertNotification.
func (c *FakeAlertNotifications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AlertNotification, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(alertnotificationsResource, c.ns, name, pt, data, subresources...), &v1alpha1.AlertNotification{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.AlertNotification), err
}
