/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubernetes-grafana-controller/pkg/apis/grafana/v1alpha1"
	scheme "kubernetes-grafana-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// AlertNotificationsGetter has a method to return a AlertNotificationInterface.
// A group's client should implement this interface.
type AlertNotificationsGetter interface {
	AlertNotifications(namespace string) AlertNotificationInterface
}

// AlertNotificationInterface has methods to work with AlertNotification resources.
type AlertNotificationInterface interface {
	Create(*v1alpha1.AlertNotification) (*v1alpha1.AlertNotification, error)
	Update(*v1alpha1.AlertNotification) (*v1alpha1.AlertNotification, error)
	UpdateStatus(*v1alpha1.AlertNotification) (*v1alpha1.AlertNotification, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.AlertNotification, error)
	List(opts v1.ListOptions) (*v1alpha1.AlertNotificationList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AlertNotification, err error)
	AlertNotificationExpansion
}

// alertNotifications implements AlertNotificationInterface
type alertNotifications struct {
	client rest.Interface
	ns     string
}

// newAlertNotifications returns a AlertNotifications
func newAlertNotifications(c *GrafanaV1alpha1Client, namespace string) *alertNotifications {
	return &alertNotifications{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the alertNotification, and returns the corresponding alertNotification object, and an error if there is any.
func (c *alertNotifications) Get(name string, options v1.GetOptions) (result *v1alpha1.AlertNotification, err error) {
	result = &v1alpha1.AlertNotification{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alertnotifications").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of AlertNotifications that match those selectors.
func (c *alertNotifications) List(opts v1.ListOptions) (result *v1alpha1.AlertNotificationList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.AlertNotificationList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("alertnotifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested alertNotifications.
func (c *alertNotifications) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("alertnotifications").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a alertNotification and creates it.  Returns the server's representation of the alertNotification, and an error, if there is any.
func (c *alertNotifications) Create(alertNotification *v1alpha1.AlertNotification) (result *v1alpha1.AlertNotification, err error) {
	result = &v1alpha1.AlertNotification{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("alertnotifications").
		Body(alertNotification).
		Do().
		Into(result)
	return
}

// Update takes the representation of a alertNotification and updates it. Returns the server's representation of the alertNotification, and an error, if there is any.
func (c *alertNotifications) Update(alertNotification *v1alpha1.AlertNotification) (result *v1alpha1.AlertNotification, err error) {
	result = &v1alpha1.AlertNotification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("alertnotifications").
		Name(alertNotification.Name).
		Body(alertNotification).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *alertNotifications) UpdateStatus(alertNotification *v1alpha1.AlertNotification) (result *v1alpha1.AlertNotification, err error) {
	result = &v1alpha1.AlertNotification{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("alertnotifications").
		Name(alertNotification.Name).
		SubResource("status").
		Body(alertNotification).
		Do().
		Into(result)
	return
}

// Delete takes name of the alertNotification and deletes it. Returns an error if one occurs.
func (c *alertNotifications) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alertnotifications").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *alertNotifications) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("alertnotifications").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched alertNotification.
func (c *alertNotifications) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.AlertNotification, err error) {
	result = &v1alpha1.AlertNotification{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("alertnotifications").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
