/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubernetes-grafana-controller/pkg/apis/grafana/v1alpha1"
	scheme "kubernetes-grafana-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// FoldersGetter has a method to return a FolderInterface.
// A group's client should implement this interface.
type FoldersGetter interface {
	Folders(namespace string) FolderInterface
}

// FolderInterface has methods to work with Folder resources.
type FolderInterface interface {
	Create(*v1alpha1.Folder) (*v1alpha1.Folder, error)
	Update(*v1alpha1.Folder) (*v1alpha1.Folder, error)
	UpdateStatus(*v1alpha1.Folder) (*v1alpha1.Folder, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.Folder, error)
	List(opts v1.ListOptions) (*v1alpha1.FolderList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Folder, err error)
	FolderExpansion
}

// folders implements FolderInterface
type folders struct {
	client rest.Interface
	ns     string
}

// newFolders returns a Folders
func newFolders(c *GrafanaV1alpha1Client, namespace string) *folders {
	return &folders{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the folder, and returns the corresponding folder object, and an error if there is any.
func (c *folders) Get(name string, options v1.GetOptions) (result *v1alpha1.Folder, err error) {
	result = &v1alpha1.Folder{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("folders").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of Folders that match those selectors.
func (c *folders) List(opts v1.ListOptions) (result *v1alpha1.FolderList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.FolderList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("folders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested folders.
func (c *folders) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("folders").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a folder and creates it.  Returns the server's representation of the folder, and an error, if there is any.
func (c *folders) Create(folder *v1alpha1.Folder) (result *v1alpha1.Folder, err error) {
	result = &v1alpha1.Folder{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("folders").
		Body(folder).
		Do().
		Into(result)
	return
}

// Update takes the representation of a folder and updates it. Returns the server's representation of the folder, and an error, if there is any.
func (c *folders) Update(folder *v1alpha1.Folder) (result *v1alpha1.Folder, err error) {
	result = &v1alpha1.Folder{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("folders").
		Name(folder.Name).
		Body(folder).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *folders) UpdateStatus(folder *v1alpha1.Folder) (result *v1alpha1.Folder, err error) {
	result = &v1alpha1.Folder{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("folders").
		Name(folder.Name).
		SubResource("status").
		Body(folder).
		Do().
		Into(result)
	return
}

// Delete takes name of the folder and deletes it. Returns an error if one occurs.
func (c *folders) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("folders").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *folders) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("folders").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched folder.
func (c *folders) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.Folder, err error) {
	result = &v1alpha1.Folder{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("folders").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
