/*
Copyright The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "kubernetes-grafana-controller/pkg/apis/grafana/v1alpha1"
	scheme "kubernetes-grafana-controller/pkg/client/clientset/versioned/scheme"
	"time"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	rest "k8s.io/client-go/rest"
)

// GrafanaNotificationChannelsGetter has a method to return a GrafanaNotificationChannelInterface.
// A group's client should implement this interface.
type GrafanaNotificationChannelsGetter interface {
	GrafanaNotificationChannels(namespace string) GrafanaNotificationChannelInterface
}

// GrafanaNotificationChannelInterface has methods to work with GrafanaNotificationChannel resources.
type GrafanaNotificationChannelInterface interface {
	Create(*v1alpha1.GrafanaNotificationChannel) (*v1alpha1.GrafanaNotificationChannel, error)
	Update(*v1alpha1.GrafanaNotificationChannel) (*v1alpha1.GrafanaNotificationChannel, error)
	UpdateStatus(*v1alpha1.GrafanaNotificationChannel) (*v1alpha1.GrafanaNotificationChannel, error)
	Delete(name string, options *v1.DeleteOptions) error
	DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error
	Get(name string, options v1.GetOptions) (*v1alpha1.GrafanaNotificationChannel, error)
	List(opts v1.ListOptions) (*v1alpha1.GrafanaNotificationChannelList, error)
	Watch(opts v1.ListOptions) (watch.Interface, error)
	Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GrafanaNotificationChannel, err error)
	GrafanaNotificationChannelExpansion
}

// grafanaNotificationChannels implements GrafanaNotificationChannelInterface
type grafanaNotificationChannels struct {
	client rest.Interface
	ns     string
}

// newGrafanaNotificationChannels returns a GrafanaNotificationChannels
func newGrafanaNotificationChannels(c *GrafanaV1alpha1Client, namespace string) *grafanaNotificationChannels {
	return &grafanaNotificationChannels{
		client: c.RESTClient(),
		ns:     namespace,
	}
}

// Get takes name of the grafanaNotificationChannel, and returns the corresponding grafanaNotificationChannel object, and an error if there is any.
func (c *grafanaNotificationChannels) Get(name string, options v1.GetOptions) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	result = &v1alpha1.GrafanaNotificationChannel{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		Name(name).
		VersionedParams(&options, scheme.ParameterCodec).
		Do().
		Into(result)
	return
}

// List takes label and field selectors, and returns the list of GrafanaNotificationChannels that match those selectors.
func (c *grafanaNotificationChannels) List(opts v1.ListOptions) (result *v1alpha1.GrafanaNotificationChannelList, err error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	result = &v1alpha1.GrafanaNotificationChannelList{}
	err = c.client.Get().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Do().
		Into(result)
	return
}

// Watch returns a watch.Interface that watches the requested grafanaNotificationChannels.
func (c *grafanaNotificationChannels) Watch(opts v1.ListOptions) (watch.Interface, error) {
	var timeout time.Duration
	if opts.TimeoutSeconds != nil {
		timeout = time.Duration(*opts.TimeoutSeconds) * time.Second
	}
	opts.Watch = true
	return c.client.Get().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		VersionedParams(&opts, scheme.ParameterCodec).
		Timeout(timeout).
		Watch()
}

// Create takes the representation of a grafanaNotificationChannel and creates it.  Returns the server's representation of the grafanaNotificationChannel, and an error, if there is any.
func (c *grafanaNotificationChannels) Create(grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	result = &v1alpha1.GrafanaNotificationChannel{}
	err = c.client.Post().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		Body(grafanaNotificationChannel).
		Do().
		Into(result)
	return
}

// Update takes the representation of a grafanaNotificationChannel and updates it. Returns the server's representation of the grafanaNotificationChannel, and an error, if there is any.
func (c *grafanaNotificationChannels) Update(grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	result = &v1alpha1.GrafanaNotificationChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		Name(grafanaNotificationChannel.Name).
		Body(grafanaNotificationChannel).
		Do().
		Into(result)
	return
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().

func (c *grafanaNotificationChannels) UpdateStatus(grafanaNotificationChannel *v1alpha1.GrafanaNotificationChannel) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	result = &v1alpha1.GrafanaNotificationChannel{}
	err = c.client.Put().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		Name(grafanaNotificationChannel.Name).
		SubResource("status").
		Body(grafanaNotificationChannel).
		Do().
		Into(result)
	return
}

// Delete takes name of the grafanaNotificationChannel and deletes it. Returns an error if one occurs.
func (c *grafanaNotificationChannels) Delete(name string, options *v1.DeleteOptions) error {
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		Name(name).
		Body(options).
		Do().
		Error()
}

// DeleteCollection deletes a collection of objects.
func (c *grafanaNotificationChannels) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	var timeout time.Duration
	if listOptions.TimeoutSeconds != nil {
		timeout = time.Duration(*listOptions.TimeoutSeconds) * time.Second
	}
	return c.client.Delete().
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		VersionedParams(&listOptions, scheme.ParameterCodec).
		Timeout(timeout).
		Body(options).
		Do().
		Error()
}

// Patch applies the patch and returns the patched grafanaNotificationChannel.
func (c *grafanaNotificationChannels) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.GrafanaNotificationChannel, err error) {
	result = &v1alpha1.GrafanaNotificationChannel{}
	err = c.client.Patch(pt).
		Namespace(c.ns).
		Resource("grafananotificationchannels").
		SubResource(subresources...).
		Name(name).
		Body(data).
		Do().
		Into(result)
	return
}
